### PR TITLE
feat(TableCell): add expand prop so table columns can be stretched

### PR DESCRIPTION
**Pull request by benji6**
This change is required to meet a design requirement on an axiom table. As far as I'm aware this is the way to achieve an expanded column in a table, but open to other suggestions if anyone has them. Thanks!

### CODE REVIEW

**Comment by pmsorhaindo** [comment]
looks good, just unsure of whether the property name `expand` follows convention.

**Comment by benji6** [comment]
yeah I'm not really sure what convention is on this. There is a `shrink` property in the Grid component so maybe the opposite is `expand`?

**Comment by benji6** [comment]
Had a chat with @pmsorhaindo maybe we rename `expand` to `grow`? Then we have `shrink` and `grow` which is the same terminology used by flexbox. Thoughts?

**Comment by pmsorhaindo** [comment]
That feels better to me. :)

**Pull request merged**
